camera_name: hik_camera_1
Camera:
  # 相机序列号(可在MVS软件内查看) # 00G16304066
  serial_number: DA5627115
  # 相机内参文件 package://my_cameras/calibrations/${NAME}.yaml
  cam_info_url: package://hik_camera_driver/config/camera_1_info.yaml
  # 帧率 (软触发时候生效)
  frame_rate: 10.0

  # ROI区域设置
  Height: 1080
  Width: 1440
  OffsetX: 0
  OffsetY: 0

  # 下采样设置（1 为不开启下采样， 2 4 分别对2倍下采样、4倍下采样。开启下采样胡，对应的ROI区域也需要进行同步缩小，具体值参考MVS结果）
  DecimationHorizontal: 1
  DecimationVertical: 1

  # 触发模式
  Trigger: true
  # 触发源
  # 0:Line0
  # 1:Line1
  # 2:Line2
  # 3.Line3
  # 4:Counter0
  # 7:Software
  # 8:FrequencyConverter
  Tigger_line: 2
  # 触发上升沿、下降沿、高电平、低电平等
  # 0:RisingEdge
  # 1:FallingEdge
  # 2:LevelHigh
  # 3:LevelLow
  Trigger_action: 2
  # 触发延时 ≥0.0 ，单位 us
  Trigger_delay: 0.0

  # 自动曝光
  # 0:Off
  # 1:Once
  # 2:Continuous
  Exposure: 0
  # 曝光时间 ≥0.0 ，单位 us 5000
  Exposure_time: 5000
  # 自动曝光时间上限
  ExposureTimeUp: 10000
  # 自动曝光时间下限
  ExposureTimeLow: 100
  # 程序控制曝光，仅当自动曝光设为手动时启用
  Exposure_control: false

  # 自动增益自动增益
  # 0:Off
  # 1:Once
  # 2:Continuous
  Gain_mode: 0
  # 增益值 ≥0.0 ，单位 dB
  Gain_value: 16.0

  # 数字偏移使能
  Digital_shift_mode: false
  # 数字偏移调节 ≥ 0.0 
  Digital_shift: 3.0
  # 亮度 0 <= L <= 255
  brightneess: 100

  # Gamma 使能
  GammaEnable: true
  # 伽马调节
  Gamma_value: 1.0
  # Gamma 选择
  Gamma_selector: 1
